# Generated by Django 3.2.6 on 2021-08-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='use_form',
            new_name='use_from',
        ),
    ]
