# Generated by Django 3.2.6 on 2021-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('useremail', models.EmailField(max_length=128, verbose_name='Useremail')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='AddDate')),
                ('gender', models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별')),
                ('job', models.CharField(choices=[('P', '교수/강사(Professor/Lecturer)'), ('S', '학생(Student)'), ('R', '연구원(Researcher)'), ('E', '기타(Etc.)')], max_length=1, verbose_name='직업')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
    ]
